services:
  - type: web
    name: puppeteer-app
    env: node
    buildCommand: |
      apt-get update && apt-get install -y \
        chromium \
        fonts-liberation \
        libappindicator3-1 \
        libatk-bridge2.0-0 \
        libatspi2.0-0 \
        libcups2 \
        libxcomposite1 \
        libxrandr2 \
        xdg-utils
      npm install
    startCommand: npm run start
